### ISSUE TITLE
After 3 days the mirror breaks down. So here is a helper for anyone encountering the same issue.,

### ISSUE THREAD

**Issue by cocoonkid** [4nte/mqtt-mirror#6]
After 3 days the mirror breaks down. So here is a helper for anyone encountering the same issue.

I haven't got time to research the underlying issue, but this way it happily mirrors away for 30days and counting.

This basically restarts the mirror container once every 24hrs.
```
services:
  mqtt_mirror:
    container_name: mqtt-mirror
    restart: unless-stopped
    image: antegulin/mqtt-mirror
    command: ./mqtt-mirror --source tcp://host.docker.internal:1883  --target tcp:/<target>:1883
    extra_hosts:
      - "host.docker.internal:host-gateway"


  restarter:
    container_name: restarter
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: /bin/sh -c "while true; do sleep 86400; docker restart mqtt-mirror && echo \"mqtt-mirror restarted at \$(date)\"; done"
    ports: []
    restart: unless-stopped
```
